### ISSUE TITLE
--validate throws an npm error if translation is invalid

### ISSUE THREAD

**Issue by sebudde** [skolmer/i18n-tag-schema#6]
`i18n-tag-schema ./translations --validate --schema ./translation.schema.json` throws an npm error if translation is invalid

![image](https://cloud.githubusercontent.com/assets/651147/17890541/f6cb5b00-6936-11e6-8a86-071911851885.png)

**Comment by skolmer** [comment]
@sebudde This is an expected behavior of npm if a cli process exits with an error code.

**Comment by sebudde** [comment]
ok. but in that case the script should not exit with an error 'cause having unknown or missing keys is not an "error" in my general understanding of errors.

**Comment by skolmer** [comment]
It is a validation error because it checks for **required** keys and fails if those keys are missing. The cli returns an error code in this case to stop execution of following commands. 
If you only want to deploy your application if all translations are valid this can be very handy. If you use the CLI like `npm run validate-translations && npm run deploy`, the deploy script will not run if the validation fails.
